### ISSUE TITLE
RSS support?

### ISSUE THREAD

**Issue by gnull** [dikmax/dikmax.name#5]
Yo @dikmax,

Does your blog support RSS feeds? I couldn't find it after randomly following a few links there.

Ivan

**Comment by dikmax** [comment]
Sure it does. <https://dikmax.name/feed.rss>

Older browsers used to show icon in address bar, when there's a feed. But now I need explicit icon somewhere on page.

Thanks for pointing out!

**Comment by gnull** [comment]
Thank you!
